### ISSUE TITLE
Can you help me with this code? Where you get green functions?

### ISSUE THREAD

**Issue by profMastermind** [nicklinyi/qssp#1]
Hi Nick,

I am working on a research and tried ti run qssp from your repo. I ran into error for not finding Green functions

$ ./qssp ./demo/qssp2017-fig01.inp 
 ######################################################
 #                                                    #
 #               Welcome to the program               #
 #                                                    #
 #    QQQQ         SSSSS        SSSSS       PPPPP     #
 #   Q    Q       S            S            P    P    #
 #   Q    Q        SSSS         SSSS        PPPPP     #
 #   Q   QQ            S            S       P         #
 #    QQQQQ       SSSSS        SSSSS        P         #
 #                                                    #
 #          Complete synthetic seismograms            #
 #      (displacement/strain/stress/rotation)         #
 #                     based on                       #
 #          a spherically symmetric earth model       #
 #                                                    #
 #                  (Version 2017)                    #
 #   Last update (correction of errors): 2018-8-10    #
 #                                                    #
 #                      by                            #
 #                 Rongjiang Wang                     #
 #              (wang@gfz-potsdam.de)                 #
 #                                                    #
 #              Helmholtz Centre Potsdam              #
 #    GFZ German Research Centre for Geosciences      #
 #           Last modified: September 2017            #
 #                                                    #
 ######################################################
                                                       
  No      R(km)   Vp(km/s)   Vs(km/s) Ro(g/cm^3)      Qp      Qs g(m/s^2)
   1  6371.0000     5.8000     3.2000     2.6000  1456.0   600.0   9.8246    R 
      6356.0000     5.8000     3.2000     2.6000  1456.0   600.0   9.8383
   2  6356.0000     6.8000     3.9000     2.9000  1350.0   600.0   9.8383      
      6346.6000     6.8000     3.9000     2.9000  1350.0   600.0   9.8445
   3  6346.6000     8.1106     4.4909     3.3808  1446.0   600.0   9.8445      
      6331.0000     8.1012     4.4849     3.3791  1446.0   600.0   9.8488
   4  6331.0000     8.1012     4.4849     3.3791  1446.0   600.0   9.8488      
      6311.0000     8.0891     4.4772     3.3769  1447.0   600.0   9.8545
   5  6311.0000     8.0891     4.4772     3.3769  1447.0   600.0   9.8545      
      6291.0000     8.0769     4.4695     3.3747   195.0    80.0   9.8604
   6  6291.0000     8.0769     4.4695     3.3747   195.0    80.0   9.8604      
      6256.0000     8.0554     4.4564     3.3709   195.0    80.0   9.8715
   7  6256.0000     8.0554     4.4564     3.3709   195.0    80.0   9.8715      
      6221.0000     8.0337     4.4436     3.3671   195.0    80.0   9.8835
   8  6221.0000     8.0337     4.4436     3.3671   195.0    80.0   9.8835      
      6186.0000     8.0118     4.4311     3.3633   195.0    80.0   9.8963
   9  6186.0000     8.0118     4.4311     3.3633   195.0    80.0   9.8963      
      6161.0000     7.9960     4.4224     3.3606   195.0    80.0   9.9060
  10  6161.0000     7.9960     4.4224     3.3606   195.0    80.0   9.9060 S    
      6151.0000     7.9897     4.4189     3.3595   195.0    80.0   9.9100
  11  6151.0000     8.5590     4.6439     3.4358   362.0   143.0   9.9100      
      6128.5000     8.6022     4.6597     3.4492   363.5   143.0   9.9177
  12  6128.5000     8.6022     4.6597     3.4492   363.5   143.0   9.9177      
      6106.0000     8.6455     4.6754     3.4626   365.0   143.0   9.9255
  13  6106.0000     8.6455     4.6754     3.4626   365.0   143.0   9.9255      
      6061.0000     8.7321     4.7069     3.4895   367.0   143.0   9.9413
  14  6061.0000     8.7321     4.7069     3.4895   367.0   143.0   9.9413      
      6016.0000     8.8187     4.7384     3.5164   370.0   143.0   9.9574
  15  6016.0000     8.8187     4.7384     3.5164   370.0   143.0   9.9574      
      5971.0000     8.9052     4.7699     3.5433   372.0   143.0   9.9738
  16  5971.0000     9.1340     4.9326     3.7238   366.0   143.0   9.9738      
      5954.3333     9.2193     4.9812     3.7448   365.7   143.0   9.9774
  17  5954.3333     9.2193     4.9812     3.7448   365.7   143.0   9.9774      
      5937.6667     9.3046     5.0298     3.7658   365.3   143.0   9.9809
  18  5937.6667     9.3046     5.0298     3.7658   365.3   143.0   9.9809      
      5921.0000     9.3899     5.0784     3.7868   365.0   143.0   9.9842
  19  5921.0000     9.3899     5.0784     3.7868   365.0   143.0   9.9842      
      5904.3333     9.4752     5.1270     3.8078   364.7   143.0   9.9874
  20  5904.3333     9.4752     5.1270     3.8078   364.7   143.0   9.9874      
      5887.6667     9.5606     5.1757     3.8288   364.3   143.0   9.9906
  21  5887.6667     9.5606     5.1757     3.8288   364.3   143.0   9.9906      
      5871.0000     9.6459     5.2243     3.8498   364.0   143.0   9.9935
  22  5871.0000     9.6459     5.2243     3.8498   364.0   143.0   9.9935      
      5854.3333     9.7312     5.2729     3.8708   363.7   143.0   9.9964
  23  5854.3333     9.7312     5.2729     3.8708   363.7   143.0   9.9964      
      5837.6667     9.8166     5.3215     3.8918   363.3   143.0   9.9992
  24  5837.6667     9.8166     5.3215     3.8918   363.3   143.0   9.9992      
      5821.0000     9.9019     5.3701     3.9128   363.0   143.0  10.0018
  25  5821.0000     9.9019     5.3701     3.9128   363.0   143.0  10.0018      
      5804.3333     9.9872     5.4187     3.9338   362.7   143.0  10.0044
  26  5804.3333     9.9872     5.4187     3.9338   362.7   143.0  10.0044      
      5787.6667    10.0725     5.4674     3.9548   362.3   143.0  10.0068
  27  5787.6667    10.0725     5.4674     3.9548   362.3   143.0  10.0068      
      5771.0000    10.1578     5.5160     3.9758   362.0   143.0  10.0091
  28  5771.0000    10.1578     5.5160     3.9758   362.0   143.0  10.0091      
      5736.0000    10.2120     5.5431     3.9840   362.0   143.0  10.0141
  29  5736.0000    10.2120     5.5431     3.9840   362.0   143.0  10.0141      
      5701.0000    10.2662     5.5702     3.9921   362.0   143.0  10.0196
  30  5701.0000    10.7513     5.9451     4.3807   759.0   312.0  10.0196      
      5684.0000    10.8042     5.9948     4.3913   754.0   312.0  10.0169
  31  5684.0000    10.8042     5.9948     4.3913   754.0   312.0  10.0169      
      5667.0000    10.8572     6.0445     4.4018   749.0   312.0  10.0143
  32  5667.0000    10.8572     6.0445     4.4018   749.0   312.0  10.0143      
      5650.0000    10.9101     6.0942     4.4124   744.0   312.0  10.0116
  33  5650.0000    10.9101     6.0942     4.4124   744.0   312.0  10.0116      
      5633.3333    10.9619     6.1430     4.4227   739.3   312.0  10.0090
  34  5633.3333    10.9619     6.1430     4.4227   739.3   312.0  10.0090      
      5616.6667    11.0138     6.1917     4.4329   734.7   312.0  10.0064
  35  5616.6667    11.0138     6.1917     4.4329   734.7   312.0  10.0064      
      5600.0000    11.0656     6.2405     4.4432   730.0   312.0  10.0039
  36  5600.0000    11.0656     6.2405     4.4432   730.0   312.0  10.0039      
      5550.0000    11.1553     6.2757     4.4734   733.5   312.0   9.9963
  37  5550.0000    11.1553     6.2757     4.4734   733.5   312.0   9.9963      
      5500.0000    11.2449     6.3109     4.5037   737.0   312.0   9.9890
  38  5500.0000    11.2449     6.3109     4.5037   737.0   312.0   9.9890      
      5450.0000    11.3302     6.3445     4.5334   740.0   312.0   9.9819
  39  5450.0000    11.3302     6.3445     4.5334   740.0   312.0   9.9819      
      5400.0000    11.4156     6.3781     4.5631   743.0   312.0   9.9751
  40  5400.0000    11.4156     6.3781     4.5631   743.0   312.0   9.9751      
      5350.0000    11.4970     6.4102     4.5922   746.5   312.0   9.9687
  41  5350.0000    11.4970     6.4102     4.5922   746.5   312.0   9.9687      
      5300.0000    11.5783     6.4423     4.6213   750.0   312.0   9.9627
  42  5300.0000    11.5783     6.4423     4.6213   750.0   312.0   9.9627      
      5250.0000    11.6560     6.4730     4.6499   752.5   312.0   9.9572
  43  5250.0000    11.6560     6.4730     4.6499   752.5   312.0   9.9572      
      5200.0000    11.7336     6.5037     4.6784   755.0   312.0   9.9521
  44  5200.0000    11.7336     6.5037     4.6784   755.0   312.0   9.9521      
      5150.0000    11.8078     6.5331     4.7065   758.0   312.0   9.9476
  45  5150.0000    11.8078     6.5331     4.7065   758.0   312.0   9.9476      
      5100.0000    11.8821     6.5625     4.7346   761.0   312.0   9.9438
  46  5100.0000    11.8821     6.5625     4.7346   761.0   312.0   9.9438      
      5050.0000    11.9533     6.5907     4.7622   763.5   312.0   9.9406
  47  5050.0000    11.9533     6.5907     4.7622   763.5   312.0   9.9406      
      5000.0000    12.0245     6.6189     4.7898   766.0   312.0   9.9381
  48  5000.0000    12.0245     6.6189     4.7898   766.0   312.0   9.9381      
      4950.0000    12.0929     6.6460     4.8170   768.0   312.0   9.9365
  49  4950.0000    12.0929     6.6460     4.8170   768.0   312.0   9.9365      
      4900.0000    12.1613     6.6732     4.8442   770.0   312.0   9.9357
  50  4900.0000    12.1613     6.6732     4.8442   770.0   312.0   9.9357      
      4850.0000    12.2272     6.6994     4.8710   772.5   312.0   9.9358
  51  4850.0000    12.2272     6.6994     4.8710   772.5   312.0   9.9358      
      4800.0000    12.2932     6.7255     4.8978   775.0   312.0   9.9370
  52  4800.0000    12.2932     6.7255     4.8978   775.0   312.0   9.9370      
      4750.0000    12.3570     6.7508     4.9242   777.0   312.0   9.9392
  53  4750.0000    12.3570     6.7508     4.9242   777.0   312.0   9.9392      
      4700.0000    12.4208     6.7761     4.9507   779.0   312.0   9.9425
  54  4700.0000    12.4208     6.7761     4.9507   779.0   312.0   9.9425      
      4650.0000    12.4827     6.8006     4.9769   781.5   312.0   9.9471
  55  4650.0000    12.4827     6.8006     4.9769   781.5   312.0   9.9471      
      4600.0000    12.5447     6.8251     5.0030   784.0   312.0   9.9531
  56  4600.0000    12.5447     6.8251     5.0030   784.0   312.0   9.9531      
      4550.0000    12.6051     6.8490     5.0289   786.0   312.0   9.9604
  57  4550.0000    12.6051     6.8490     5.0289   786.0   312.0   9.9604      
      4500.0000    12.6655     6.8729     5.0547   788.0   312.0   9.9692
  58  4500.0000    12.6655     6.8729     5.0547   788.0   312.0   9.9692      
      4450.0000    12.7247     6.8963     5.0803   790.0   312.0   9.9796
  59  4450.0000    12.7247     6.8963     5.0803   790.0   312.0   9.9796      
      4400.0000    12.7839     6.9196     5.1059   792.0   312.0   9.9917
  60  4400.0000    12.7839     6.9196     5.1059   792.0   312.0   9.9917      
      4300.0000    12.9005     6.9654     5.1567   795.0   312.0  10.0215
  61  4300.0000    12.9005     6.9654     5.1567   795.0   312.0  10.0215      
      4200.0000    13.0158     7.0105     5.2071   799.0   312.0  10.0594
  62  4200.0000    13.0158     7.0105     5.2071   799.0   312.0  10.0594      
      4100.0000    13.1306     7.0553     5.2573   803.0   312.0  10.1066
  63  4100.0000    13.1306     7.0553     5.2573   803.0   312.0  10.1066      
      4000.0000    13.2453     7.0997     5.3072   807.0   312.0  10.1641
  64  4000.0000    13.2453     7.0997     5.3072   807.0   312.0  10.1641      
      3900.0000    13.3607     7.1442     5.3571   811.0   312.0  10.2334
  65  3900.0000    13.3607     7.1442     5.3571   811.0   312.0  10.2334      
      3800.0000    13.4774     7.1889     5.4068   815.0   312.0  10.3158
  66  3800.0000    13.4774     7.1889     5.4068   815.0   312.0  10.3158      
      3700.0000    13.5960     7.2340     5.4566   819.0   312.0  10.4130
  67  3700.0000    13.5960     7.2340     5.4566   819.0   312.0  10.4130      
      3630.0000    13.6804     7.2660     5.4915   822.0   312.0  10.4909
  68  3630.0000    13.6804     7.2660     5.4915   822.0   312.0  10.4909      
      3600.0000    13.6875     7.2658     5.5064   823.0   312.0  10.5270
  69  3600.0000    13.6875     7.2658     5.5064   823.0   312.0  10.5270      
      3500.0000    13.7117     7.2649     5.5564   826.0   312.0  10.6599
  70  3500.0000    13.7117     7.2649     5.5564   826.0   312.0  10.6599      
      3480.0000    13.7166     7.2647     5.5665   826.0   312.0  10.6890
  71  3480.0000     8.0648     0.0000     9.9035 57822.0     0.0  10.6890      
      3440.0000     8.1321     0.0000     9.9665 57822.0     0.0  10.6019
  72  3440.0000     8.1321     0.0000     9.9665 57822.0     0.0  10.6019      
      3400.0000     8.1994     0.0000    10.0294 57822.0     0.0  10.5135
  73  3400.0000     8.1994     0.0000    10.0294 57822.0     0.0  10.5135      
      3350.0000     8.2798     0.0000    10.1054 57822.0     0.0  10.4012
  74  3350.0000     8.2798     0.0000    10.1054 57822.0     0.0  10.4012      
      3300.0000     8.3602     0.0000    10.1813 57822.0     0.0  10.2870
  75  3300.0000     8.3602     0.0000    10.1813 57822.0     0.0  10.2870      
      3250.0000     8.4366     0.0000    10.2543 57822.0     0.0  10.1710
  76  3250.0000     8.4366     0.0000    10.2543 57822.0     0.0  10.1710      
      3200.0000     8.5130     0.0000    10.3273 57822.0     0.0  10.0530
  77  3200.0000     8.5130     0.0000    10.3273 57822.0     0.0  10.0530      
      3150.0000     8.5855     0.0000    10.3973 57822.0     0.0   9.9333
  78  3150.0000     8.5855     0.0000    10.3973 57822.0     0.0   9.9333      
      3100.0000     8.6581     0.0000    10.4673 57822.0     0.0   9.8118
  79  3100.0000     8.6581     0.0000    10.4673 57822.0     0.0   9.8118      
      3050.0000     8.7269     0.0000    10.5344 57822.0     0.0   9.6886
  80  3050.0000     8.7269     0.0000    10.5344 57822.0     0.0   9.6886      
      3000.0000     8.7957     0.0000    10.6015 57822.0     0.0   9.5638
  81  3000.0000     8.7957     0.0000    10.6015 57822.0     0.0   9.5638      
      2950.0000     8.8610     0.0000    10.6658 57822.0     0.0   9.4372
  82  2950.0000     8.8610     0.0000    10.6658 57822.0     0.0   9.4372      
      2900.0000     8.9263     0.0000    10.7301 57822.0     0.0   9.3091
  83  2900.0000     8.9263     0.0000    10.7301 57822.0     0.0   9.3091      
      2850.0000     8.9883     0.0000    10.7916 57822.0     0.0   9.1795
  84  2850.0000     8.9883     0.0000    10.7916 57822.0     0.0   9.1795      
      2800.0000     9.0502     0.0000    10.8532 57822.0     0.0   9.0484
  85  2800.0000     9.0502     0.0000    10.8532 57822.0     0.0   9.0484      
      2750.0000     9.1089     0.0000    10.9120 57822.0     0.0   8.9157
  86  2750.0000     9.1089     0.0000    10.9120 57822.0     0.0   8.9157      
      2700.0000     9.1675     0.0000    10.9709 57822.0     0.0   8.7817
  87  2700.0000     9.1675     0.0000    10.9709 57822.0     0.0   8.7817      
      2650.0000     9.2231     0.0000    11.0271 57822.0     0.0   8.6463
  88  2650.0000     9.2231     0.0000    11.0271 57822.0     0.0   8.6463      
      2600.0000     9.2787     0.0000    11.0834 57822.0     0.0   8.5095
  89  2600.0000     9.2787     0.0000    11.0834 57822.0     0.0   8.5095      
      2550.0000     9.3315     0.0000    11.1370 57822.0     0.0   8.3715
  90  2550.0000     9.3315     0.0000    11.1370 57822.0     0.0   8.3715      
      2500.0000     9.3842     0.0000    11.1907 57822.0     0.0   8.2322
  91  2500.0000     9.3842     0.0000    11.1907 57822.0     0.0   8.2322      
      2450.0000     9.4342     0.0000    11.2418 57822.0     0.0   8.0917
  92  2450.0000     9.4342     0.0000    11.2418 57822.0     0.0   8.0917      
      2400.0000     9.4841     0.0000    11.2930 57822.0     0.0   7.9500
  93  2400.0000     9.4841     0.0000    11.2930 57822.0     0.0   7.9500      
      2354.0000     9.5788     0.0000    11.3904 57822.0     0.0   7.8177
  94  2354.0000     9.5788     0.0000    11.3904 57822.0     0.0   7.8177      
      2200.0000     9.6687     0.0000    11.4831 57822.0     0.0   7.3678
  95  2200.0000     9.6687     0.0000    11.4831 57822.0     0.0   7.3678      
      2100.0000     9.7539     0.0000    11.5712 57822.0     0.0   7.0729
  96  2100.0000     9.7539     0.0000    11.5712 57822.0     0.0   7.0729      
      2000.0000     9.8350     0.0000    11.6548 57822.0     0.0   6.7746
  97  2000.0000     9.8350     0.0000    11.6548 57822.0     0.0   6.7746      
      1900.0000     9.9121     0.0000    11.7340 57822.0     0.0   6.4733
  98  1900.0000     9.9121     0.0000    11.7340 57822.0     0.0   6.4733      
      1800.0000     9.9855     0.0000    11.8090 57822.0     0.0   6.1696
  99  1800.0000     9.9855     0.0000    11.8090 57822.0     0.0   6.1696      
      1700.0000    10.0557     0.0000    11.8799 57822.0     0.0   5.8641
 100  1700.0000    10.0557     0.0000    11.8799 57822.0     0.0   5.8641      
      1600.0000    10.1229     0.0000    11.9468 57822.0     0.0   5.5573
 101  1600.0000    10.1229     0.0000    11.9468 57822.0     0.0   5.5573      
      1500.0000    10.1874     0.0000    12.0099 57822.0     0.0   5.2501
 102  1500.0000    10.1874     0.0000    12.0099 57822.0     0.0   5.2501      
      1400.0000    10.2496     0.0000    12.0692 57822.0     0.0   4.9435
 103  1400.0000    10.2496     0.0000    12.0692 57822.0     0.0   4.9435      
      1300.0000    10.3097     0.0000    12.1250 57822.0     0.0   4.6389
 104  1300.0000    10.3097     0.0000    12.1250 57822.0     0.0   4.6389      
      1221.5000    10.3557     0.0000    12.1663 57822.0     0.0   4.4023
 105  1221.5000    11.0283     3.5043    12.7636   445.0    85.0   4.4023      
      1200.0000    11.0364     3.5100    12.7749   445.0    85.0   4.3271
 106  1200.0000    11.0364     3.5100    12.7749   445.0    85.0   4.3271      
      1100.0000    11.0725     3.5352    12.8250   443.0    85.0   3.9757
 107  1100.0000    11.0725     3.5352    12.8250   443.0    85.0   3.9757      
      1000.0000    11.1054     3.5582    12.8707   440.0    85.0   3.6220
 108  1000.0000    11.1054     3.5582    12.8707   440.0    85.0   3.6220      
       900.0000    11.1352     3.5791    12.9121   439.0    85.0   3.2660
 109   900.0000    11.1352     3.5791    12.9121   439.0    85.0   3.2660      
       800.0000    11.1619     3.5977    12.9491   437.0    85.0   2.9081
 110   800.0000    11.1619     3.5977    12.9491   437.0    85.0   2.9081      
       700.0000    11.1854     3.6141    12.9818   436.0    85.0   2.5484
 111   700.0000    11.1854     3.6141    12.9818   436.0    85.0   2.5484      
       600.0000    11.2058     3.6284    13.0101   434.0    85.0   2.1872
 112   600.0000    11.2058     3.6284    13.0101   434.0    85.0   2.1872      
       500.0000    11.2230     3.6404    13.0340   433.0    85.0   1.8247
 113   500.0000    11.2230     3.6404    13.0340   433.0    85.0   1.8247      
       400.0000    11.2371     3.6503    13.0536   432.0    85.0   1.4611
 114   400.0000    11.2371     3.6503    13.0536   432.0    85.0   1.4611      
       300.0000    11.2481     3.6579    13.0689   432.0    85.0   1.0966
 115   300.0000    11.2481     3.6579    13.0689   432.0    85.0   1.0966      
       200.0000    11.2559     3.6634    13.0798   431.0    85.0   0.7314
 116   200.0000    11.2559     3.6634    13.0798   431.0    85.0   0.7314      
       100.0000    11.2606     3.6667    13.0863   431.0    85.0   0.3658
 117   100.0000    11.2606     3.6667    13.0863   431.0    85.0   0.3658      
         0.0000    11.2622     3.6678    13.0885   431.0    85.0   0.0000
At line 132 of file qpgrnspec.f (unit = 21)
Fortran runtime error: Cannot open file './GreenFunctions/U_Green_210km': No such file or directory

Error termination. Backtrace:
#0  0x7f4b7c33c32a
#1  0x7f4b7c33ced5
#2  0x7f4b7c33d69d
#3  0x7f4b7c4afecd
#4  0x7f4b7c4b0214
#5  0x55ee6d689fb1
#6  0x55ee6d7398df
#7  0x55ee6d739c86
#8  0x7f4b7b99bc86
#9  0x55ee6d614329
#10  0xffffffffffffffff
 

Regards

**Comment by nicklinyi** [comment]
Hi, I just tried to reproduce your results. This error is caused by that there's no `GreenFunctions` folder where you ran this code. One simple solution to solve your problem is 
```
$ mkdir GreenFunctions
$ ./qssp ./demo/qssp2017-fig01.inp
```
It should fix your problem.

**Comment by profMastermind** [comment]
Great Thanks
